drop schema public if exists cascade;
--^ powyzsza linijke zakomentowac jezeli chce sie generowac schema automatycznie.

create table if not exists "category"
(
  "id"           bigint generated by default as identity (start with 1),
  "desc"         varchar(255),
  "is_alcoholic" boolean,
  "name"         varchar(255),
  primary key ("id")
);


create table if not exists "drink"
(
  "id"           bigint generated by default as identity (start with 1),
  "desc"         varchar(255),
  "is_available" boolean,
  "name"         varchar(255),
  "price"        numeric(19, 2),
  primary key ("id")
);

create table if not exists "drink_categories"
(
  "id"          bigint generated by default as identity (start with 1),
  "category_id" bigint,
  "drink_id"    bigint,
  primary key ("id")
);


alter table "drink_categories"
  add constraint "constraint_1"
    foreign key ("category_id")
      references "category";

alter table "drink_categories"
  add constraint "constraint_2"
    foreign key ("drink_id")
      references "drink";
